From https://github.com/zekelabs/machine-learning-for-beginners/wiki/NumPy-Problems

    Create a null array of size 10 but the fifth value which is 1
    Reverse a above created array (first element becomes last)
    Create a 3x3 matrix with values ranging from 0 to 8
    Find indices of non-zero elements from [1,2,0,0,4,0]
    Create a 3x3x3 array with random values
    Create a 10x10 array with random values and find the minimum and maximum values
    Create a random vector of size 30 and find the mean value
    Create a 2d array with 1 on the border and 0 inside
    Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
    Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
    Extract the integer part of a random array
    Create a 5x5 matrix with row values ranging from 0 to 4
    Create a random vector of size 10 and sort it
    Consider two random array A anb B, check if they are equal
    How to tell if a given 2D array has null columns?
    Considering a four dimensions array, how to get sum over the last two axis at once?
    Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
    Extract all the contiguous 3x3 blocks from a random 10x10 matrix
    How to compute averages using a sliding window over an array?
    Consider a 16x16 array, how to get the block-sum (block size is 4x4)?


In [1]:
import numpy as np

In [2]:
#    Create a null array of size 10 but the fifth value which is 1
a = np.array([0,0,0,0,1,0,0,0,0,0])

In [3]:
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [7]:
#    Reverse a above created array (first element becomes last)
np.flipud(a)

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [8]:
a[::-1]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [9]:
#    Create a 3x3 matrix with values ranging from 0 to 8
a = np.random.randint(0,8,(3,3))

In [10]:
a

array([[1, 5, 2],
       [6, 1, 1],
       [1, 5, 7]])

In [21]:
#    Find indices of non-zero elements from [1,2,0,0,4,0]
tmp = np.array([1,2,0,0,4,0]);
tmp

array([1, 2, 0, 0, 4, 0])

In [22]:
a = np.array(tmp) 
b = list(a)
for val in b:
    if val != 0:
        print(b.index(val))

0
1
4


In [23]:
#    Create a 3x3x3 array with random values
np.random.randint(0,8,(3,3,3))

array([[[7, 0, 3],
        [0, 0, 3],
        [0, 6, 4]],

       [[4, 1, 1],
        [6, 2, 6],
        [0, 6, 2]],

       [[1, 0, 1],
        [6, 7, 1],
        [1, 1, 6]]])

In [28]:
#    Create a 10x10 array with random values and find the minimum and maximum values
a = np.random.randint(0,8,(10,10)) 
print(a)
a.min()
a.max()

[[5 7 4 6 1 4 6 7 3 3]
 [2 3 3 5 3 1 4 0 7 3]
 [7 6 0 2 3 2 7 2 3 0]
 [6 6 6 5 7 0 0 4 7 0]
 [4 2 1 4 6 0 2 1 6 2]
 [0 4 5 2 6 2 5 7 7 6]
 [3 3 3 5 1 2 1 3 3 4]
 [0 2 5 7 0 3 3 3 1 7]
 [3 7 3 2 3 4 2 7 3 1]
 [6 7 7 5 3 7 1 6 3 3]]


7

In [29]:
#    Create a random vector of size 30 and find the mean value
a = np.random.randint(0,8,(30)) 
a.mean()

3.466666666666667

In [32]:
#    Create a 2d array with 1 on the border and 0 inside
a = np.ones((4,4))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [34]:
#    Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
a = np.random.randint(0,10,(6,7,8))

In [39]:
## Dont know

In [42]:
#    Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.randint(0,5,(5,3)) 
b = np.random.randint(0,5,(3,2)) 
np.matmul(a,b)


array([[15,  5],
       [21,  5],
       [11,  4],
       [14,  3],
       [16,  4]])

In [43]:
#    Extract the integer part of a random array
#dont know

In [46]:
#    Create a 5x5 matrix with row values ranging from 0 to 4
a = np.random.randint(0,5,(5,5))
a

array([[1, 0, 4, 1, 0],
       [0, 3, 2, 1, 0],
       [0, 4, 3, 2, 1],
       [2, 3, 1, 2, 3],
       [2, 2, 4, 0, 4]])

In [50]:
#    Create a random vector of size 10 and sort it
a = np.random.randint(0,5,(10))
a.sort()
a

array([0, 0, 0, 0, 1, 1, 2, 3, 3, 4])

In [54]:
#    Consider two random array A anb B, check if they are equal
a = np.random.randint(0,5,(10))
b = np.random.randint(0,5,(10))
print(a)
print(b)
print(a == b)
np.array_equal(a,b)

[4 2 2 0 3 2 3 1 0 4]
[3 0 3 0 4 0 1 2 2 3]
[False False False  True False False False False False False]


False

In [56]:
#    How to tell if a given 2D array has null columns?
a = np.random.randint(0,5,(4,4))
np.isnan(a).any()


False

In [57]:
#    Considering a four dimensions array, how to get sum over the last two axis at once?
a = np.random.randint(0,5,(4,4,4,4))
#dont know

In [58]:
#TODO
Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
    Extract all the contiguous 3x3 blocks from a random 10x10 matrix
    How to compute averages using a sliding window over an array?
    Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

SyntaxError: invalid syntax (<ipython-input-58-4f491fd45cb0>, line 2)

In [63]:
#Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
a = np.random.randint(0,5,(5,5,3))
b = np.random.randint(0,5,(5,5))
b*a
#dont know

ValueError: operands could not be broadcast together with shapes (5,5) (5,5,3) 