In [2]:
import numpy as np
a = np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
np.empty(shape=(2,2), dtype=int)

array([[1914708000, 1920300133],
       [1918115950,  168453493]])

In [7]:
np.ones_like(a)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
b=np.full(fill_value='helo',shape=(2,2))

In [13]:
b

array([['helo', 'helo'],
       ['helo', 'helo']], dtype='<U4')

In [15]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [16]:
np.arange(5,0,-1)

array([5, 4, 3, 2, 1])

In [17]:
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [18]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [19]:
np.random.rand(10)

array([0.65328425, 0.24158816, 0.92026819, 0.39444512, 0.32452982,
       0.02989568, 0.94257721, 0.22049981, 0.28245386, 0.62224683])

In [21]:
data = np.random.randint(2,10,(3,3))

In [22]:
data

array([[5, 2, 7],
       [4, 9, 9],
       [7, 7, 5]])

In [23]:
data.ndim

2

In [24]:
data.shape

(3, 3)

In [25]:
data.size

9

In [26]:
a=np.array([1,2,3,4,5])

In [27]:
a

array([1, 2, 3, 4, 5])

In [28]:
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
a.reshape(5,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [30]:
a = np.random.randint(2,10,(4,4))

In [31]:
a

array([[8, 4, 2, 4],
       [8, 3, 3, 7],
       [7, 4, 6, 4],
       [5, 3, 5, 4]])

In [34]:
#-1 will make it select the required size to match 2 column
a.reshape(-1,2)

array([[8, 4],
       [2, 4],
       [8, 3],
       [3, 7],
       [7, 4],
       [6, 4],
       [5, 3],
       [5, 4]])

In [35]:
#accessing data
a = np.random.randint(2,10,(5,5))

In [36]:
a

array([[8, 2, 4, 7, 4],
       [4, 8, 8, 7, 2],
       [8, 5, 6, 9, 8],
       [7, 9, 6, 5, 9],
       [2, 9, 9, 7, 3]])

In [38]:
a[:,2:4]

array([[4, 7],
       [8, 7],
       [6, 9],
       [6, 5],
       [9, 7]])

In [39]:
a[1:3,:]

array([[4, 8, 8, 7, 2],
       [8, 5, 6, 9, 8]])

In [40]:
a[1:4,1:4]

array([[8, 8, 7],
       [5, 6, 9],
       [9, 6, 5]])

In [42]:
#flatens to 1 diamention
a.ravel()

array([8, 2, 4, 7, 4, 4, 8, 8, 7, 2, 8, 5, 6, 9, 8, 7, 9, 6, 5, 9, 2, 9,
       9, 7, 3])

In [43]:
np.hstack([a,a])

array([[8, 2, 4, 7, 4, 8, 2, 4, 7, 4],
       [4, 8, 8, 7, 2, 4, 8, 8, 7, 2],
       [8, 5, 6, 9, 8, 8, 5, 6, 9, 8],
       [7, 9, 6, 5, 9, 7, 9, 6, 5, 9],
       [2, 9, 9, 7, 3, 2, 9, 9, 7, 3]])

In [44]:
np.vstack([a,a])

array([[8, 2, 4, 7, 4],
       [4, 8, 8, 7, 2],
       [8, 5, 6, 9, 8],
       [7, 9, 6, 5, 9],
       [2, 9, 9, 7, 3],
       [8, 2, 4, 7, 4],
       [4, 8, 8, 7, 2],
       [8, 5, 6, 9, 8],
       [7, 9, 6, 5, 9],
       [2, 9, 9, 7, 3]])

In [45]:
np.hsplit(a,[3])
#returns two arrays

[array([[8, 2, 4],
        [4, 8, 8],
        [8, 5, 6],
        [7, 9, 6],
        [2, 9, 9]]), array([[7, 4],
        [7, 2],
        [9, 8],
        [5, 9],
        [7, 3]])]

In [46]:
u,v,w = np.vsplit(a,[2,4])

In [47]:
u

array([[8, 2, 4, 7, 4],
       [4, 8, 8, 7, 2]])

In [48]:
w

array([[2, 9, 9, 7, 3]])

In [49]:
v

array([[8, 5, 6, 9, 8],
       [7, 9, 6, 5, 9]])

In [50]:
#functions

In [52]:
np.sum([a,a])

312

In [53]:
a

array([[8, 2, 4, 7, 4],
       [4, 8, 8, 7, 2],
       [8, 5, 6, 9, 8],
       [7, 9, 6, 5, 9],
       [2, 9, 9, 7, 3]])

In [54]:
np.mean(a)

6.24

In [55]:
np.median(a)

7.0

In [56]:
a= np.array([3,4,5,6,7])

In [57]:
a

array([3, 4, 5, 6, 7])

In [58]:
np.cumsum(a)

array([ 3,  7, 12, 18, 25], dtype=int32)

In [59]:
np.argmax(a)
#position of maximum value

4

In [60]:
np.max(a)
#maximum value in a array

7

In [61]:
d=np.random.randint(2,20,(4,4))

In [62]:
d

array([[ 3,  9,  5, 15],
       [ 7, 17, 15,  3],
       [18, 11, 19, 12],
       [12, 13,  3, 14]])

In [63]:
np.argmax(d,axis=1)

array([3, 1, 2, 3], dtype=int64)

In [65]:
#transpose
np.transpose(a)

array([3, 4, 5, 6, 7])

In [66]:
a

array([3, 4, 5, 6, 7])

In [67]:
np.matmul(a,a)

135

In [68]:
np.std(a)

1.4142135623730951

In [71]:
help(np.transpose)

Help on function transpose in module numpy.core.fromnumeric:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpos

In [72]:
d = np.array([1,2,3,4])

In [74]:
d1 = np.reshape(d,(4,1,1,1))

In [75]:
d1

array([[[[1]]],


       [[[2]]],


       [[[3]]],


       [[[4]]]])

In [76]:
np.squeeze(d1)

array([1, 2, 3, 4])

In [78]:
np.choose(a=[0,1,0,0,1], choices=['hello','hi'])

array(['hello', 'hi', 'hello', 'hello', 'hi'], dtype='<U5')

In [79]:
#broadcasting

In [81]:
a = np.array([1,2,3,4])

In [82]:
a

array([1, 2, 3, 4])

In [83]:
a+a

array([2, 4, 6, 8])

In [84]:
a+5

array([6, 7, 8, 9])

In [85]:
a

array([1, 2, 3, 4])

In [86]:
# 5 is scalar, a is vector. broadcast 5 as scalar to vector [5,5,5,5]

In [87]:
b = np.array([[1,1,1,1],[2,2,2,2]])

In [88]:
b

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [89]:
b.shape

(2, 4)

In [90]:
a.shape

(4,)

In [91]:
a+b

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [93]:
c = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [94]:
c

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [95]:
b+c

ValueError: operands could not be broadcast together with shapes (2,4) (3,4) 

In [96]:
b.reshape(1,2,4) + c.reshape(3,1,4)

array([[[2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5]]])

In [97]:
b

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [102]:
b.reshape(1,2,4)

array([[[1, 1, 1, 1],
        [2, 2, 2, 2]]])

In [99]:
b.shape

(2, 4)

In [105]:
b=np.array([[1,2],[3,4]])

In [106]:
b

array([[1, 2],
       [3, 4]])

In [107]:
b.shape

(2, 2)

In [108]:
b.reshape(2,1,2)

array([[[1, 2]],

       [[3, 4]]])

In [109]:
a=np.array([[5,5],[6,6],[7,7]])

In [110]:
b=np.array([[1,1],[2,2]])

In [111]:
a

array([[5, 5],
       [6, 6],
       [7, 7]])

In [112]:
b

array([[1, 1],
       [2, 2]])

In [113]:
a.shape

(3, 2)

In [114]:
b.shape

(2, 2)

In [115]:
a1 = a.reshape(1,3,2)
a1

array([[[5, 5],
        [6, 6],
        [7, 7]]])

In [116]:
b1 = b.reshape(2,1,2)
b1

array([[[1, 1]],

       [[2, 2]]])

In [117]:
c1 = a1 - b1
c1

array([[[4, 4],
        [5, 5],
        [6, 6]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

In [118]:
a1.shape

(1, 3, 2)

In [119]:
b1.shape

(2, 1, 2)

In [120]:
b.shape

(2, 2)

In [121]:
a = np.random.randint(1,3,(5,3))

In [122]:
a

array([[2, 2, 2],
       [2, 2, 1],
       [2, 1, 2],
       [1, 1, 2],
       [1, 2, 2]])

In [123]:
b = np.random.randint(1,3,(3,4,2))

In [124]:
b

array([[[1, 1],
        [2, 2],
        [1, 2],
        [1, 1]],

       [[2, 1],
        [1, 1],
        [2, 2],
        [2, 2]],

       [[1, 1],
        [1, 2],
        [2, 1],
        [2, 1]]])

In [126]:
a1 = a.reshape(5,3,1,1)

In [127]:
b1 = b.reshape(1,3,4,2)

In [128]:
c1=a1+b1

In [129]:
c1

array([[[[3, 3],
         [4, 4],
         [3, 4],
         [3, 3]],

        [[4, 3],
         [3, 3],
         [4, 4],
         [4, 4]],

        [[3, 3],
         [3, 4],
         [4, 3],
         [4, 3]]],


       [[[3, 3],
         [4, 4],
         [3, 4],
         [3, 3]],

        [[4, 3],
         [3, 3],
         [4, 4],
         [4, 4]],

        [[2, 2],
         [2, 3],
         [3, 2],
         [3, 2]]],


       [[[3, 3],
         [4, 4],
         [3, 4],
         [3, 3]],

        [[3, 2],
         [2, 2],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 4],
         [4, 3],
         [4, 3]]],


       [[[2, 2],
         [3, 3],
         [2, 3],
         [2, 2]],

        [[3, 2],
         [2, 2],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 4],
         [4, 3],
         [4, 3]]],


       [[[2, 2],
         [3, 3],
         [2, 3],
         [2, 2]],

        [[4, 3],
         [3, 3],
         [4, 4],
         [4, 4]],

        [[3,